# version: 2.1
# jobs:
#   build:
#     docker:
#       -image: circleci/node:latest
#     working_directory: ~/circleci-workflows
#     setps:
#       - checkout
#       - run: npm install -g yarn
#       - run: echo "----- install dependencies -----"
#       - run: yarn install
#       - save_cache:
#         key: v1-dependencies-{{ checksum "package.json" }}
#         paths:
#           - node_modules
#       - run: echo "----- build -----"
#       - run: yarn build
#       - run: echo "----- deploy -----"
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             - v1-dependencies
#       - add_ssh_keys:
#         fingerprints:
#           - '22:64:53:e5:25:0e:52:fb:75:d6:50:33:b7:ba:9b:47'
#       - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
#       - run: pwd
#       - deploy:
#         name: deploy
#         command: |
#           if [ "${CIRCLE_BRANCH}" = "master" ]; then
#             scp -r public $SSH_USER@SSH_IP:~
#           else
#             echo "Not master branch, dry run only"
#       - run: echo "----- deploy done -----"
# # workflows:
# #   version: 2
# #   scheduled-workflow:
# #     # triggers:
# #     #   - shedule:
# #     #     cron: '0 0 * * *'
# #     #     filters:
# #     #       branches:
# #     #         only: master
# #     jobs:
# #       - run: echo "test"
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.20.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "----- `node -v` -----"
      - run: echo "----- `npm -v` -----"
      - run: echo "----- install dependencies -----"
      - run: npm install
      - run: echo "----- build -----"
      - run: yarn build
      - run: sudo apt-get update && sudo apt-get install rsync
      - run: echo "----- deploy -----"
      - add_ssh_keys:
        fingerprints:
          - '22:64:53:e5:25:0e:52:fb:75:d6:50:33:b7:ba:9b:47'
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run: ls
      # - run:
      #   name: deploy
      #   command: |
      #     if [ "${CIRCLE_BRANCH}" = "master" ]; then
      #       scp -r public $SSH_USER@SSH_IP:~
      #     else
      #       echo "Not master branch, dry run only"
      - run: echo "----- deploy done -----"
